[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
include = "\\.pyi?$|eta_utility/*|test/*"
exclude = "\\.xlsx?$"
line_length = 120
target_version = ["py36","py37","py38"]

[tool.isort]
profile = "black"
multi_line_output = 3
