config = {  # noqa: INP001
    "setup": {
        "environment_import": "eta_utility.eta_x.envs.BaseEnvMPC",
        "agent_import": "eta_utility.eta_x.agents.MPCBasic",
        "interaction_env_class": "BaseEnvMPC",
        "interaction_env_package": "eta_utility.eta_x.envs",
        "vectorizer_class": "DummyVecEnv",
        "vectorizer_package": "stable_baselines3.common.vec_env.dummy_vec_env",
        "policy_class": "NoPolicy",
        "policy_package": "eta_utility.eta_x.common",
    },
    "paths": {"relpath_results": "results", "relpath_scenarios": "scenarios"},
    "settings": {
        "sampling_time": 10,
        "episode_duration": 1800,
        "n_episodes_play": 1,
        "n_environments": 1,
        "verbose": 2,
        "seed": 123,
    },
    "environment_specific": {
        "scenario_time_begin": "2022-03-18 00:00",
        "scenario_time_end": "2022-03-18 00:30",
        "sim_steps_per_sample": 1,
        "scenario_files": [
            {
                "path": "electricity_price_test.csv",
                "interpolation_method": "ffill",
                "resample_method": "asfreq",
                "time_conversion_str": "%d.%m.%Y %H:%M",
            }
        ],
        "prediction_scope": 1200,
        "model_parameters": {
            "N": 5,
            "n_start": 1,
            "S": 1200,
            "p_heat": 10,
            "p_int": 1,
            "p_clean": 4,
            "p_dry": 8,
            "durationStart": 10,
            "durationCleaning": 600,
            "durationDrying": 120,
            "durationLoading": 240,
            "tankTemperatureMin": 55,
            "tankTemperatureMax": 65,
            "tankTemperatureStart": 60,
            "temperatureChangeHeatingValue": 0.033,
            "temperatureChangeCleaningValue": -0.025,
        },
    },
    "interaction_env_specific": {"scenario_time_begin": "2022-03-18 06:00", "scenario_time_end": "2022-03-18 10:00"},
    "agent_specific": {"action_index": 1, "solver_name": "cplex_direct"},
}
